- hosts: ec2_RabbitMQ
  become: True
  tasks:
    - name: Install Rabbit MQ
      shell: |
            sh -c "echo 'deb http://www.rabbitmq.com/debian/ testing main' >/etc/apt/sources.list.d/rabbitmq.list";
            wget http://www.rabbitmq.com/rabbitmq-signing-key-public.asc
            apt-key add rabbitmq-signing-key-public.asc
            rm rabbitmq-signing-key-public.asc
            apt-get update
            apt-get install rabbitmq-server

    - name: Enable admin gui
      shell: rabbitmq-plugins enable rabbitmq_management

    - name: Add initial user
      shell: |
            rabbitmqctl add_user sparlor welcome1
            rabbitmqctl set_user_tags sparlor administrator
