- hosts: ec2_RabbitMQ
  become: True
  tasks:
    - name: Install Rabbit MQ
      shell: |
            apt-get update -y
            apt-get install curl gnupg -y
            curl -fsSL https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc | apt-key add -
            apt-get install apt-transport-https
            tee /etc/apt/sources.list.d/bintray.rabbitmq.list <<EOF
            deb https://dl.bintray.com/rabbitmq-erlang/debian bionic erlang
            deb https://dl.bintray.com/rabbitmq/debian bionic main
            EOF
            apt-get update -y
            apt-get install rabbitmq-server -y --fix-missing
    
    - name: Start RMQ
      shell: service rabbitmq-server start

    - name: Enable admin gui
      shell: rabbitmq-plugins enable rabbitmq_management

    - name: Add initial user
      shell: |
            rabbitmqctl add_user sparlor welcome1
            rabbitmqctl set_user_tags sparlor administrator
